In [58]:
import empiricaldist
import os

print(os.path.dirname(empiricaldist.__file__))

/Users/saadmanchowdhury/Desktop/All Github projects/.venv/lib/python3.14/site-packages/empiricaldist

## Snippet 1- Download helper for chapter support code
Before the chapter can load and analyze NSFG survey data, the notebook first defines a tiny helper that downloads a local copy of the shared `thinkstats.py` support module if it is missing. This matches the chapter’s opening workflow: get the environment ready, then move on to reading, checking, and exploring the data.

In [41]:

""" 
Reading the Data
Context: this helper makes sure the notebook has the local support file it needs before later cells import from it
Plain-English: it checks whether a file already exists, and if not, downloads it from the book's GitHub repository

"""
# os stand for operating system module
# path used for manipulating file and directory paths.
# like checking if a file exists, getting file names, joining paths, etc.
# basename returns the base name of the file with its extension from the given path
# exists function returns True if the file or directory exists 
# basename function creates the local filename by taking the last path segment from the URL with 1 parameter URL (string datatype)
# urllib is a library used for working with URLs (Uniform Resource Locators). 
# urllib.request module used for opening and reading URLs and also used to send HTTP requests and handle responses. 
# urlretrieve() function allows to download the file from the URL and save it locally under the chosen filename with 2 parameters (string)


# import one function to pull a filename from an online URL, and one to check whether that file is already present

from os.path import basename, exists  

# Define a reusable helper function that takes a single parameter: URL str(string representing the file to download)

def download(url):
    filename = basename(url)  # Extract the filename from the URL

    print(f" Downloaded {filename} from URL") # To check whether the file already exists in the current directory
     
    if not exists(filename):
        from urllib.request import urlretrieve  
        # Import the downloader only when needed

        local, _ = urlretrieve(url, filename)  
        # fetch the file from the URL and save it locally under the chosen filename

        print("Downloaded " + local)
    # return object of urlretrieve is 2 items which are (filename, headers) where headers is metadata from the server

download("https://github.com/AllenDowney/ThinkStats/raw/v3/nb/thinkstats.py")  # fetch the shared helper module used by later notebook cells

# To get current working directory
import os
cwd = os.getcwd()
print("Current Working Directory:", cwd)


"""
Interpretation: running this cell either creates a new local file named `thinkstats.py` or leaves the existing copy in place. 
If the cell prints a download message, a file was just written to disk; 
if it prints nothing, the file was already available and memory now contains the `download` function for later reuse. 
A common error here is a network or permission failure, which usually means the notebook cannot reach the URL or cannot write files in the current environment.


* Note you can import py files from your Github or somebody else's, 
by navigating to the file online and clicking raw button and then copying URL from it so you can execute download function to put new file in your cwd

"""


print()

 Downloaded thinkstats.py from URL
Current Working Directory: /Users/saadmanchowdhury/Desktop/All Github projects/01._eda_and_regression/drafts

In [42]:
""" 
we should always verify file correctness (file vs folder), not just existence, before using it in data. 
If we accidentally created a folder workflows or filename that already exists as a directory, Python does NOT overwrite it.
exists() returns True for BOTH files & folders but it doesn't differentiate between whether the path is a file or a directory.
This could lead to errors when we try to work with that "file," which is actually a folder.
"""

from os.path import basename, isfile, isdir  
# basename extracts filename; 
# isfile checks real files; 
# isdir detects incorrect folder state

import shutil  # needed to remove directories safely

def download(url):  # define helper that safely downloads a file from a URL
    filename = basename(url)  # extract local filename from URL
    print("Downloaded " + filename + " from URL")
    
    if isdir(filename):  # check if a folder exists where a file should be
        shutil.rmtree(filename)  # remove the folder to fix incorrect state
    
    if not isfile(filename):  # only download if a valid file does not already exist
        from urllib.request import urlretrieve  # import downloader only when needed
        
        local, _ = urlretrieve(url, filename)  # download file and save locally
        print("Downloaded " + local)  # confirm successful download

download("https://github.com/AllenDowney/ThinkStats/raw/v3/nb/thinkstats.py")  # ensure support module is available

Downloaded thinkstats.py from URL

## Snippet 2- Ensure empirical distribution library is available
Before working with distributions later in the chapter, the notebook ensures that the `empiricaldist` library is available. This follows the book’s practical approach: install lightweight tools on demand so distribution analysis can run smoothly without manual setup.

In [43]:
"""
Data Loading
Context: this snippet ensures a required library is available before later cells rely on it for distribution and stata-style dictionary related computations
Plain-English: it tries to import a library and installs it automatically if it is missing
Reappears: yes; on-demand installation patterns appear in other chapters and projects

"""
# Both "empiricaldist" and "statadict" are the third-party library from thinkstats.py.
# "empiricaldist" library is used for working with empirical distributions and 
# "statadict" library is  for reading and parsing Stata-style data dictionary.
# try is a control flow statement used to handle errors (known as exceptions) that may occur during the execution of any program
# %pip is a magic command used in Jupyter notebooks and IPython environments (such as JupyterLab) to install Python packages


try:
    import empiricaldist  # attempt to load the empiricaldist package into memory
    
except ImportError:  # catch the specific error raised when the package is not installed
    %pip install empiricaldist  # use notebook magic to install the package into the current environment


try:
    import statadict  # attempt to load statadict for reading Stata-style data dictionary files
except ImportError:  # run this block if the package is not installed
    %pip install statadict  # install statadict into the current environment



""""
Interpretation: 
This cell either loads the both empiricaldist and statadict package or installs it if it is not already available.
If the packages are already installed, the cell runs silently with no output.
If installation is needed, pip output will appear showing download and install progress.
After execution, both empiricaldist and statadict becomes available for import in later cells.
A common issue is network failure during installation, which prevents pip from downloading the package.
Another issue is environment restrictions where package installation is not permitted.

"""

print()

## Snippet 3- Import core libraries and helper utilities
With the helper module in place, the notebook now loads the main libraries and helper tools used throughout the chapter. This prepares the environment for working with data tables, numerical arrays, visualizations, and formatted outputs as the exploratory analysis begins.

In [44]:
""""
Data Loading
Context: this snippet prepares all core libraries and helper utilities that later cells depend on for analysis and visualization
Plain-English: it loads libraries for data handling, numerical computation, plotting, and display formatting
Reappears: yes; these libraries and helpers are used repeatedly across this chapter and later chapters

"""

# IPython is an interactive shell that allows to interactively work with Python, commonly used in Jupyter Notebooks
# IPython.display module helps to display rich media content in a formatted and structured way.
# such as HTML, images, videos, LaTeX equations, etc.
# HTML() function takes a string of HTML code and displays it within Jupyter Notebooks 
# HTML elements like headers, paragraphs, links, images, tables, and other formatted content, directly in the notebook output


import numpy as np  # load NumPy as np for numerical operations on arrays
import pandas as pd  # load pandas as pd for working with tabular data using DataFrames
import matplotlib.pyplot as plt  # load plotting interface as plt for creating charts

from IPython.display import HTML  # import HTML utility to render formatted output in notebook cells
from thinkstats import decorate  # import decorate helper to standardize plot labels and styling


""""
Interpretation:   This cell loads five tools into memory: np, pd, plt, HTML, and decorate.
There is no visible output when it runs successfully, which is expected.
These imports enable data manipulation (pandas), numerical work (NumPy), plotting (Matplotlib),
rich display (HTML), and consistent plot formatting (decorate).
A common error is ModuleNotFoundError for thinkstats, indicating the support file is missing.
Another possible issue is missing libraries, which would raise ImportError and require installation.

"""

print()

## Snippet 4- Download NSFG dataset files for analysis
Before loading the dataset, the notebook ensures that the raw NSFG data files are available locally. These files include the data dictionary and compressed survey data, which the chapter uses to construct the DataFrame for analysis.

In [45]:
""""  
Data Loading
Context: this snippet ensures the required dataset files exist locally before the data-loading function depends on them
Plain-English: it downloads the survey data files if they are not already present
Real-world: this pattern appears in data pipelines where raw datasets are fetched before processing begins
Reappears: yes; dataset download and setup steps recur in other data-driven chapters

"""
download("https://github.com/AllenDowney/ThinkStats/raw/v3/data/2002FemPreg.dct")  # download the data dictionary file describing column structure
download("https://github.com/AllenDowney/ThinkStats/raw/v3/data/2002FemPreg.dat.gz")  # download the compressed raw dataset file

# Interpretation
# This cell checks whether each dataset file exists locally and downloads it only if missing.
# If downloads occur, messages will print confirming the saved files.
# If no output appears, the files were already present, which is expected in some environments.
# After this step, the required data files are available for ReadFemPreg to load into a DataFrame.
# A common error is a network issue preventing download, or file permission issues blocking writes to the directory.

Downloaded 2002FemPreg.dct from URL
Downloaded 2002FemPreg.dat.gz from URL

## Snippet 5- Store the dataset filenames in variables
With the raw NSFG files available locally, the notebook assigns their names to variables. This makes the next data-reading step clearer because later code can refer to the dictionary file and data file by purpose rather than repeating raw strings.

In [46]:
"""  
Data Loading
Context: this snippet creates named references to the two downloaded files so the reader function can use them cleanly in the next step
Plain-English: it stores the dictionary filename and compressed data(main data) filename in variables
Reappears: using variables for file paths comes back throughout data-loading workflows

"""
dct_file = "2002FemPreg.dct"  
# create a variable holding the local filename of the Stata-style data dictionary

dat_file = "2002FemPreg.dat.gz"  
# create a variable holding the local filename of the compressed raw data file

"""   
Interpretation: this cell creates two string variables in memory, `dct_file` and `dat_file`.
 There is no visible output, which is normal.
 Later cells will pass these names into the data-reading function instead of repeating the filenames directly. 
 A common error here is a typo in a filename string, which usually leads to a file-not-found error only when a later cell tries to open the file.

 """
import os

print("Exists:", os.path.exists("2002FemPreg.dct"))
print("Is file:", os.path.isfile("2002FemPreg.dct"))
print("Is dir:", os.path.isdir("2002FemPreg.dct"))

Exists: True
Is file: True
Is dir: False

## Snippet 6- Define function to read NSFG data using the data dictionary
Instead of loading the dataset directly, the notebook defines a reusable function that reads the data dictionary and applies it to parse the raw fixed-width file correctly. This reflects the book’s approach of understanding structure first, then building a clean and repeatable data-loading step.

In [47]:
"""
Data Loading
Context: this snippet defines how to read the dataset and then uses that logic to load it into memory
Plain-English: it builds a function to parse structured raw data and immediately applies it to create a DataFrame
Reappears: yes; custom loaders and immediate usage appear throughout data workflows

"""
# statadict is a third-party library from thinkstats.py. 
# it allows to read, interpret and parse Stata-Style data dictionary files and extract metadata from them. 
# parse_stata_dict function in statadict used to parse a Stata dictionary file (usually .dct extension)
# it reads the dictionary file and extract the metadata (like Column names, Column types, Value labels, Variable labels etc) of the dataset
# read_stata is a function from pandas library. it reads Stata .dta files (Stata data files) directly into a pandas DataFrame.
# To correctly interpret the structure of the data file (e.g., determine where each variable starts and ends in the fixed-width format)
# stata dictionary file (dct_file) and data file (dat_file) are the parameters of the function


from statadict import parse_stata_dict  # import parser for reading Stata-style dictionary files

def read_stata(dct_file, dat_file):  # define function to read dataset using dictionary metadata
    stata_dict = parse_stata_dict(dct_file)  # extract column names and column positions from dictionary file

    # pandas.read_fwf() is used to read fixed-width formatted files 
    # where each column has a fixed width rather than separated by commas or tabs
    # Read fixed-width formatted file into a DataFrame based on column names and column position extracted from dct_file
    
    resp = pd.read_fwf(  
        dat_file,  # path to compressed raw dataset file
        names=stata_dict.names,  # assign column names from dictionary
        colspecs=stata_dict.colspecs,  # assign column boundaries from dictionary
        compression="gzip",  # specify common gzip file (.gz file) compressed version of the original file
    )
    
    return resp  # return the resulting DataFrame

preg = read_stata(dct_file, dat_file)  # call the function to load dataset into variable preg
print(preg)  



"""
Interpretation:
The result is a DataFrame, which is a Pandas data structure that represents tabular data in rows and columns.
This cell first defines the read_stata function, then immediately uses it to create a DataFrame named preg.
dct_file and dat_file are input files that are processed inside this function to create the DataFrame.
The dataset has 243 variables with information about 13,593 pregnancies.
The function ensures the raw data is correctly interpreted using metadata from the dictionary file.
The resulting DataFrame contains structured survey data ready for analysis.
No output is shown unless explicitly displayed.
Common errors include missing files, incorrect paths, or issues with dictionary parsing leading to misaligned data.

"""

print()

       caseid  pregordr  howpreg_n  howpreg_p  moscurrp  nowprgdk  pregend1  \
0           1         1        NaN        NaN       NaN       NaN       6.0
1           1         2        NaN        NaN       NaN       NaN       6.0
2           2         1        NaN        NaN       NaN       NaN       5.0
3           2         2        NaN        NaN       NaN       NaN       6.0
4           2         3        NaN        NaN       NaN       NaN       6.0
...       ...       ...        ...        ...       ...       ...       ...
13588   12571         1        NaN        NaN       NaN       NaN       6.0
13589   12571         2        NaN        NaN       NaN       NaN       3.0
13590   12571         3        NaN        NaN       NaN       NaN       3.0
13591   12571         4        NaN        NaN       NaN       NaN       6.0
13592   12571         5        NaN        NaN       NaN       NaN       6.0

       pregend2  nbrnaliv  multbrth  ...  poverty_i  laborfor_i  religion_i  \
0           NaN       1.0       NaN  ...          0           0           0
1           NaN       1.0       NaN  ...          0           0           0
2           NaN       3.0       5.0  ...          0           0           0
3           NaN       1.0       NaN  ...          0           0           0
4           NaN       1.0       NaN  ...          0           0           0
...         ...       ...       ...  ...        ...         ...         ...
13588       NaN       1.0       NaN  ...          0           0           0
13589       NaN       NaN       NaN  ...          0           0           0
13590       NaN       NaN       NaN  ...          0           0           0
13591       NaN       1.0       NaN  ...          0           0           0
13592       NaN       1.0       NaN  ...          0           0           0

       metro_i      basewgt  adj_mod_basewgt      finalwgt  secu_p  sest  \
0            0  3410.389399      3869.349602   6448.271112       2     9
1            0  3410.389399      3869.349602   6448.271112       2     9
2            0  7226.301740      8567.549110  12999.542264       2    12
3            0  7226.301740      8567.549110  12999.542264       2    12
4            0  7226.301740      8567.549110  12999.542264       2    12
...        ...          ...              ...           ...     ...   ...
13588        0  4670.540953      5795.692880   6269.200989       1    78
13589        0  4670.540953      5795.692880   6269.200989       1    78
13590        0  4670.540953      5795.692880   6269.200989       1    78
13591        0  4670.540953      5795.692880   6269.200989       1    78
13592        0  4670.540953      5795.692880   6269.200989       1    78

       cmintvw
0         1231
1         1231
2         1231
3         1231
4         1231
...        ...
13588     1227
13589     1227
13590     1227
13591     1227
13592     1227

[13593 rows x 243 columns]

## Description of NSFG dataset:

"""
NSFG data collected to investigate "whether first babies tend to be born late and some other questions"
NSFG gathered information on family life, marriage and divorce, pregnancy, infertility, use of contraception, and men's and women's health.
Target population is US population of aged 15-44 years
cycle-6(jan 2002-march 2023)
Cross-sectional study
The NSFG dataset contains 243 variables with information about 13,593 pregnancies. Here are some of the variables we'll use for the explorations in this book.

caseid is the integer ID of the respondent.
pregordr is a pregnancy serial number: the code for a respondent's first pregnancy is 1, for the second pregnancy is 2, and so on.
prglngth is the integer duration of the pregnancy in weeks.
outcome is an integer code for the outcome of the pregnancy. The code 1 indicates a live birth.
birthord is a serial number for live births: the code for a respondent's first child is 1, and so on. For outcomes other than live birth, this field is blank.
birthwgt_lb and birthwgt_oz contain the pounds and ounces parts of the birth weight of the baby.
agepreg is the mother's age at the end of the pregnancy.
finalwgt is the statistical weight associated with the respondent. It is a floating-point value that indicates the number of people in the U.S. population this respondent represents
"""

## Snippet 7- Inspect dataset shape, columns, and sample rows
After loading the dataset, the notebook performs a quick structural check by looking at its size, column names, a small sample of rows and then focuses on a specific variable, `pregordr`, which represents the pregnancy order. This aligns with the chapter’s goal of identifying and understanding relevant variables before analysis.

In [48]:
""""   
Data Loading
Context: this snippet validates the dataset structure so later analysis is based on correctly loaded data
Plain-English: it checks how many rows and columns exist, what the column names are, and previews sample data
Reappears: yes; structural inspection is a standard first step in exploratory data analysis

"""

# shape contains the number of rows and columns
# columns contains the names of the variables

preg.shape  # returns a tuple (number of rows, number of columns)
print(preg.shape)

preg.columns  # lists all column names in the DataFrame
print("preg_col=", preg.columns)


# head displays the first few rows, by default first 5 rows
print("preg_head=", preg.head())  # display the first 5 rows for a quick data preview


# select the pregordr column (pregnancy order) from the DataFrame and store it separately
# pregordr is a pregnancy serial number: the code for a respondent's first pregnancy is 1, for the second pregnancy is 2, and so on.

pregordr = preg["pregordr"]  
print(pregordr)
print("preg_order=", pregordr.head())  # display first 5 values of the pregordr column


"""   
Interpretation:
preg.shape outputs a tuple showing dataset size: (rows, columns).
If shape shows unexpected dimensions, it may indicate parsing issues.
preg.columns outputs an index of column names, which helps verify variables are correctly parsed.
If columns look incorrect or misaligned, the dictionary parsing step may have failed.
preg.head() displays the first few rows so you can visually inspect values and structure.
If head() shows garbled or shifted data, column specifications may not match the raw file format.
pregordr extracts one column as a pandas Series representing pregnancy order.
pregordr.head() shows the first few values of this variable for inspection.
If pregordr does not exist in columns, a KeyError will occur, indicating parsing or naming issues
"""

print()

(13593, 243)
preg_col= Index(['caseid', 'pregordr', 'howpreg_n', 'howpreg_p', 'moscurrp', 'nowprgdk',
       'pregend1', 'pregend2', 'nbrnaliv', 'multbrth',
       ...
       'poverty_i', 'laborfor_i', 'religion_i', 'metro_i', 'basewgt',
       'adj_mod_basewgt', 'finalwgt', 'secu_p', 'sest', 'cmintvw'],
      dtype='str', length=243)
preg_head=    caseid  pregordr  howpreg_n  howpreg_p  moscurrp  nowprgdk  pregend1  \
0       1         1        NaN        NaN       NaN       NaN       6.0
1       1         2        NaN        NaN       NaN       NaN       6.0
2       2         1        NaN        NaN       NaN       NaN       5.0
3       2         2        NaN        NaN       NaN       NaN       6.0
4       2         3        NaN        NaN       NaN       NaN       6.0

   pregend2  nbrnaliv  multbrth  ...  poverty_i  laborfor_i  religion_i  \
0       NaN       1.0       NaN  ...          0           0           0
1       NaN       1.0       NaN  ...          0           0           0
2       NaN       3.0       5.0  ...          0           0           0
3       NaN       1.0       NaN  ...          0           0           0
4       NaN       1.0       NaN  ...          0           0           0

   metro_i      basewgt  adj_mod_basewgt      finalwgt  secu_p  sest  cmintvw
0        0  3410.389399      3869.349602   6448.271112       2     9     1231
1        0  3410.389399      3869.349602   6448.271112       2     9     1231
2        0  7226.301740      8567.549110  12999.542264       2    12     1231
3        0  7226.301740      8567.549110  12999.542264       2    12     1231
4        0  7226.301740      8567.549110  12999.542264       2    12     1231

[5 rows x 243 columns]
0        1
1        2
2        1
3        2
4        3
        ..
13588    1
13589    2
13590    3
13591    4
13592    5
Name: pregordr, Length: 13593, dtype: int64
preg_order= 0    1
1    2
2    1
3    2
4    3
Name: pregordr, dtype: int64

In [49]:
# head displays the first few rows, by default first 5 rows
preg.head()  # display the first 5 rows for a quick data preview

,caseid,pregordr,howpreg_n,howpreg_p,moscurrp,nowprgdk,pregend1,pregend2,nbrnaliv,multbrth,...,poverty_i,laborfor_i,religion_i,metro_i,basewgt,adj_mod_basewgt,finalwgt,secu_p,sest,cmintvw
0,1,1,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,0,3410.389399,3869.349602,6448.271112,2,9,1231
1,1,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,0,3410.389399,3869.349602,6448.271112,2,9,1231
2,2,1,NaN,NaN,NaN,NaN,5.0,NaN,3.0,5.0,...,0,0,0,0,7226.301740,8567.549110,12999.542264,2,12,1231
3,2,2,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,0,7226.301740,8567.549110,12999.542264,2,12,1231
4,2,3,NaN,NaN,NaN,NaN,6.0,NaN,1.0,NaN,...,0,0,0,0,7226.301740,8567.549110,12999.542264,2,12,1231

In [50]:

pregordr = preg["pregordr"]  # select the pregordr column (pregnancy order) from the DataFrame and store it separately
pregordr.head()  # display first 5 values of the pregordr column

0    1
1    2
2    1
3    2
4    3
Name: pregordr, dtype: int64

## Snippet 8- Create summary table and compare with actual data counts
To make categorical results easier to read, the notebook defines a helper that converts structured data into a formatted HTML table. 
To validate the reported category totals, the notebook displays a labeled summary table and compares it with counts computed directly from the dataset. This follows the book’s approach of checking whether derived or reported values match the raw data.

In [51]:
def show_table(d):
    """Show a table in a Jupyter notebook.

    Args:
        d: dictionary to show.

    Returns:
        HTML: HTML representation of the table.
    """
    df = pd.DataFrame(d)
    return HTML(df.to_html(index=False))

In [52]:
"""
Exploratory Data Analysis
Context: this snippet presents a formatted summary table and compares it with counts computed from the dataset
Plain-English: it builds a readable table and verifies it by counting values directly from the data
Real-world: comparing reported summaries with computed results is a standard data validation step
Reappears: yes; validation through cross-checking appears throughout analysis workflows
"""

# HTML() function (imported from IPython.display) is used to render the HTML string (created by df.to_html())
# And display it inside the Jupyter notebook. it has several optional parameters (data, url, filename, and metadata)
# df.to_html() function is used to convert the pandas DataFrame into HTML format.
# index=False argument tells pandas not to include the row indices in the HTML output, making the table cleaner
""" show_table(d) converts a dictionary → DataFrame → HTML → displays it nicely in Jupyter """


from IPython.display import display, HTML  
import pandas as pd  

def show_table(d):  # define a function that takes one parameter d, which is a dictionary of column data
    df = pd.DataFrame(d)  # convert the dictionary into a pandas DataFrame (tabular structure)
    display(HTML(df.to_html(index=False)))  # convert DataFrame to HTML and return it for display without row indices

# define a dictionary containing table data
# Dictionary d contains three keys: "Value", "Label", and "Total"
# "Total" column indicates the number of pregnancies with each outcome

d = { 
    "Value": [1, 2, 3, 4, 5, 6, "Total"],  # numeric category codes plus a total row
    "Label": [
        "LIVE BIRTH",
        "INDUCED ABORTION",
        "STILLBIRTH",
        "MISCARRIAGE",
        "ECTOPIC PREGNANCY",
        "CURRENT PREGNANCY",
        "",
    ],
    "Total": [9148, 1862, 120, 1921, 190, 352, 13593],
}

show_table(d)  # call the function to render the table in formatted HTML


# preg is a DataFrame that contains a column "outcome"
# outcome is an integer code for the outcome of the pregnancy. The code 1 indicates a live birth.
# preg["outcome"] selects the outcome column from the DataFrame
# .value_counts() counts occurrences of each unique value. It returns Series containing counts of unique values.
# The arguments of value_counts() are "normalize, sort, ascending, bins, dropna"
# .sort_index() orders the counts by category code (1–6) for comparison.
# Returns a new Series sorted by label if inplace argument is False, otherwise updates the original series and returns None.
# It will sort as many unique categories (index values) as are present in the preg["outcome"] column



preg["outcome"].value_counts().sort_index() 
print(preg["outcome"].value_counts().sort_index())


"""
Interpretation:
This cell defines a function and then uses it to display a formatted table.
pd.DataFrame(d) turns the dictionary into a structured table with columns Value, Label, and Total.
df.to_html(index=False) converts that table into HTML format without showing row indices.
display(HTML(...)) renders the table visually in the Jupyter notebook output.
The output is a clean table where each row corresponds to a pregnancy outcome category.
If the table does not render properly, it may indicate issues with HTML display support in the environment.
"""

print()  # blank print to make sure any extra output doesn't interfere

outcome
1    9148
2    1862
3     120
4    1921
5     190
6     352
Name: count, dtype: int64

## Snippet 9- Validate birth weight counts against the codebook
After checking the `outcome` variable, the notebook validates another important variable, `birthwgt_lb`, which stores birth weight in pounds. The chapter uses this step to compare the dataset with the published codebook again, and to notice special values that represent missing or inapplicable cases rather than real weights.

In [53]:
"""   
Exploratory Data Analysis
Context: this snippet displays the codebook table for birth weight and compares it with counts computed from the dataset
Plain-English: it shows expected category totals and checks them against actual values in the data
Real-world: comparing codebook summaries with computed counts is a key step in data validation and cleaning
Reappears: yes; identifying special codes for missing data is used in later cleaning steps

"""
# dictionary representing codebook summary for birth weight (in pounds)
d = {
    "Value": [".", "0-5", "6", "7", "8", "9-95", "97", "98", "99", "Total"],
    "Label": [
        "inapplicable",
        "UNDER 6 POUNDS",
        "6 POUNDS",
        "7 POUNDS",
        "8 POUNDS",
        "9 POUNDS OR MORE",
        "Not ascertained",
        "REFUSED",
        "DON'T KNOW",
        "",
    ],
    "Total": [4449, 1125, 2223, 3049, 1889, 799, 1, 1, 57, 13593],
}

show_table(d)  # display formatted codebook table for comparison


# Birth weight is only recorded for pregnancies that ended in a live birth
# preg["birthwgt_lb"] selects the birth-weight column (pounds)
# .value_counts(dropna=False) counts all values including NaN (not a number cases).
# The argument dropna : bool, default True. dropna=False means that value_counts does not ignore values that are "NA"
# .sort_index() sorts values so they align with codebook ordering

counts = preg["birthwgt_lb"].value_counts(dropna=False).sort_index()  # compute sorted counts
print(counts)  # display actual counts from dataset

"""
Interpretation:
The first output is the codebook table showing expected counts for each category of birth weight.
The second output is a Series showing actual counts from the dataset.
NaN corresponds to inapplicable cases (shown as "." in the codebook).
Values like 97, 98 and 99 represent missing or unknown responses, not real birth weights.
Comparing both outputs helps verify that the dataset matches the documented structure.
If counts differ significantly, it may indicate parsing issues or incorrect handling of missing values.
If birthwgt_lb is missing, a KeyError will occur due to earlier loading problems.

"""

print()

birthwgt_lb
0.0        8
1.0       40
2.0       53
3.0       98
4.0      229
5.0      697
6.0     2223
7.0     3049
8.0     1889
9.0      623
10.0     132
11.0      26
12.0      10
13.0       3
14.0       3
15.0       1
51.0       1
97.0       1
98.0       1
99.0      57
NaN     4449
Name: count, dtype: int64

In [54]:
# To check the counts for the weight range from 0 to 5 pounds, we can use an attribute called loc
# loc is short for "location" and a slice index to select a subset of the counts
counts.loc[0:5]
counts.loc[0:5].sum()

# The values 97, 98, and 99 represent cases where the birth weight is unknown
# We might handle missing data by using replace function. Replacing these values with NaN

preg["birthwgt_lb1"] = preg["birthwgt_lb"].replace([51, 97, 98, 99], np.nan)
print(preg["birthwgt_lb1"]) 
# The first argument is a list of values to be replaced. The second argument, np.nan, gets the NaN value from NumPy.

print()

0        8.0
1        7.0
2        9.0
3        7.0
4        6.0
        ...
13588    6.0
13589    NaN
13590    NaN
13591    7.0
13592    7.0
Name: birthwgt_lb1, Length: 13593, dtype: float64

/var/folders/cb/fffq6hxx2qvgkbh5yps70l_w0000gn/T/ipykernel_69610/1624789967.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  preg["birthwgt_lb1"] = preg["birthwgt_lb"].replace([51, 97, 98, 99], np.nan)

## Snippet 10- Transform age and birth weight, then compute summary statistics
This snippet performs key transformations on age (mother's age) and birth weight variables to convert them into meaningful units and clean invalid values. It then computes summary statistics to understand typical values after proper preprocessing, following the chapter’s workflow of preparing data before analysis.

In [55]:
"""  
 Data Transformation
Context: this snippet converts raw encoded values into usable units and computes summary statistics on cleaned data
Plain-English: it rescales age, cleans invalid weight values, combines pounds and ounces, and calculates averages
Real-world: transforming raw encoded fields into meaningful units is a common step in real-world datasets
Reappears: yes; data transformation before analysis is used throughout the book

"""

# "agepreg" contains the mother's age at the end of the pregnancy. 
# According to the codebook, agepreg is an integer number of centiyears (one hundredth of a year)
# To convert it to years, we can divide through by 100

preg["agepreg"]/= 100.0  # convert from centiyears to years
preg["agepreg"].mean()  # compute mean after conversion

print(
    "Average mother's age at the end of preg=", preg["agepreg"].mean()
    )

# birthwgt_lb and birthwgt_oz contain birth weights with the pounds and ounces in separate columns
# preg["birthwgt_oz"] selects the ounces component of birth weight
# .value_counts(dropna=False) counts all values including missing and special codes
# .sort_index() sorts values for easier inspection

print(
    preg["birthwgt_oz"].value_counts(dropna=False).sort_index()
    )  # inspect raw ounce values including invalid codes


# replace special codes with NaN so they are treated as missing
# preg["birthwgt_oz"] = preg["birthwgt_oz"].replace([97, 98, 99], np.nan) 
# *noted that* in Notebook code, the value of 99 doesn't have missing value

preg["birthwgt_oz"] = preg["birthwgt_oz"].replace([97, 98, 99], np.nan)  # clean invalid ounce values, note 97 and 98 didnt show up but waas in original notebook

print(
    preg["birthwgt_oz"]
    )


# combine pounds and ounces into a single continuous variable
# preg["birthwgt_lb"] is pounds, preg["birthwgt_oz"]/16 converts ounces to pounds

preg["totalwgt_lb"] = preg["birthwgt_lb"] + preg["birthwgt_oz"] / 16.0  # compute total birth weight in pounds
preg["totalwgt_lb"].mean()  # compute average total birth weight
print(
    preg["totalwgt_lb"].mean()
    )

"""   
Interpretation
The first mean shows age in centiyears; after dividing by 100, the second mean shows age in years.
value_counts reveals special codes (97, 98) in birthwgt_oz that must be cleaned.
replace converts these codes to NaN so they do not affect calculations.
totalwgt_lb combines pounds and ounces into a single continuous measurement.
The final mean represents the average birth weight in pounds after cleaning.
If results look unrealistic, it may indicate missing values were not handled correctly or units were misinterpreted.

"""
print()

Average mother's age at the end of preg= 24.6881511970395
birthwgt_oz
0.0     1037
1.0      408
2.0      603
3.0      533
4.0      525
5.0      535
6.0      709
7.0      501
8.0      756
9.0      505
10.0     475
11.0     557
12.0     555
13.0     487
14.0     475
15.0     378
97.0       1
98.0       1
99.0      46
NaN     4506
Name: count, dtype: int64
0        13.0
1        14.0
2         2.0
3         0.0
4         3.0
         ...
13588     3.0
13589     NaN
13590     NaN
13591     8.0
13592     8.0
Name: birthwgt_oz, Length: 13593, dtype: float64
7.270508352693882

/var/folders/cb/fffq6hxx2qvgkbh5yps70l_w0000gn/T/ipykernel_69610/2998104026.py:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  preg["totalwgt_lb"] = preg["birthwgt_lb"] + preg["birthwgt_oz"] / 16.0  # compute total birth weight in pounds

## Snippet 11- Compute summary statistics for birth weight
After transforming and cleaning the birth weight data, the notebook computes summary statistics to understand its distribution. This includes count, mean, variance, and standard deviation, following the chapter’s goal of describing key characteristics of the data numerically.

In [57]:
"""   
 Summary Statistics
Context: this snippet computes descriptive statistics manually and using built-in pandas functions to understand birth weight distribution
Plain-English: it calculates average, variance, and spread of birth weight using both formulas and library methods
Real-world: computing summary statistics is a foundational step in data analysis and model building
Reappears: yes; statistical summaries are used throughout analysis and modeling

"""
# weights.count() to count number of non-missing values (ignores NaN) 
# weights.mean() to compute mean using pandas built-in method
# weights.var() to compute variance using pandas (default uses n-1, sample variance)
# weights.var(ddof=0) when we prefer the version with n in the denominator
# "ddof" stands for Delta Degrees of Freedom for Population variance which is Divided by n
# std = np.sqrt(var) compute standard deviation as square root of variance


weights = preg["totalwgt_lb"]  # select total birth weight column
print(weights)
n = weights.count()  # count number of non-missing values (ignores NaN)
print(n)

# compute mean manually as total sum divided by count
manual_mean = weights.sum() / n  
print(manual_mean)


# compute mean using pandas built-in method
print(weights.mean())

# compute squared deviations from the mean
squared_deviations = (weights - manual_mean) ** 2

# compute population variance manually(divide by n)
manual_var = squared_deviations.sum() / n  
print(manual_var)

# compute variance using pandas (default uses n-1, sample variance)
# var method computes the mean of the squared deviations, it divides by n-1 rather than n
print(weights.var())

# If we prefer the version with n in the denominator, we can get it by passing ddof=0 as a keyword argument to the var method.
# "ddof" stands for "Delta Degrees of Freedom=0" for Population variance which is Divided by n
weights.var(ddof=0)

# compute manual standard deviation as square root of variance
manual_std = np.sqrt(manual_var)  
print(manual_std)

# compute standard deviation using pandas with population formula (ddof=0)
print(weights.std(ddof=0))


"""   
Interpretation
n shows the number of valid (non-missing) birth weight values used in calculations.
The manually computed mean matches weights.mean(), confirming correctness.
squared_deviations measures how far each value is from the mean.
var is population variance (dividing by n), while weights.var() uses sample variance (n-1).
std represents the spread of birth weights around the mean.
weights.std(ddof=0) matches the manually computed std using population formula.
If n is much smaller than total rows, it indicates many missing values were excluded.
If values seem unrealistic, it may indicate earlier cleaning steps were incorrect.

"""

print()

0        8.8125
1        7.8750
2        9.1250
3        7.0000
4        6.1875
          ...
13588    6.1875
13589       NaN
13590       NaN
13591    7.5000
13592    7.5000
Name: totalwgt_lb, Length: 13593, dtype: float64
9039
7.270508352693882
7.270508352693882
2.198076890598448
2.198320094503139
1.4825912756381807
1.4825912756381807

## Snippet 12- Inspect all records for a single respondent
To understand how the dataset is structured at the individual level, the notebook selects all records for one respondent using `caseid`. This helps verify that each row represents a pregnancy and that multiple rows can belong to the same person.

In [ ]:
"""   
Exploratory Data Analysis
Context: this snippet filters the dataset for one respondent to inspect their records across multiple pregnancies
Plain-English: it selects rows with a specific ID and checks how many records exist and their outcomes
Real-world: filtering by an identifier is common when debugging or understanding relational structure in datasets
Reappears: yes; subsetting data is used frequently in analysis

"""

# The query() method takes a string that can contain column names, comparison operators, and numbers, among other things.
subset = preg.query("caseid == 10229") # filter rows where caseid equals 10229 
print(subset)

print(subset.shape)  # display number of rows and columns for this respondent

print(subset["outcome"].values)  # extract outcome values as a NumPy array for this subset


"""   
Interpretation
subset contains all rows (pregnancies) for the respondent with caseid 10229.
subset.shape shows how many pregnancies this individual has recorded.
subset["outcome"].values shows the outcome codes for each pregnancy.
This confirms that each row is one pregnancy and multiple rows can belong to the same person.
the respondent has 7 recorded pregnancies, and the outcomes are coded as:
4 = miscarriage
1 = live birth
If subset is empty, it may indicate the caseid does not exist or data was filtered earlier.

"""

print()

       caseid  pregordr  howpreg_n  howpreg_p  moscurrp  nowprgdk  pregend1  \
11093   10229         1        NaN        NaN       NaN       NaN       1.0
11094   10229         2        NaN        NaN       NaN       NaN       1.0
11095   10229         3        NaN        NaN       NaN       NaN       1.0
11096   10229         4        NaN        NaN       NaN       NaN       1.0
11097   10229         5        NaN        NaN       NaN       NaN       1.0
11098   10229         6        NaN        NaN       NaN       NaN       1.0
11099   10229         7        NaN        NaN       NaN       NaN       6.0

       pregend2  nbrnaliv  multbrth  ...  religion_i  metro_i      basewgt  \
11093       NaN       NaN       NaN  ...           0        0  1914.323805
11094       NaN       NaN       NaN  ...           0        0  1914.323805
11095       NaN       NaN       NaN  ...           0        0  1914.323805
11096       NaN       NaN       NaN  ...           0        0  1914.323805
11097       NaN       NaN       NaN  ...           0        0  1914.323805
11098       NaN       NaN       NaN  ...           0        0  1914.323805
11099       NaN       1.0       NaN  ...           0        0  1914.323805

       adj_mod_basewgt     finalwgt  secu_p  sest  cmintvw  birthwgt_lb1  \
11093      2021.999794  3369.662656       2    65     1232           NaN
11094      2021.999794  3369.662656       2    65     1232           NaN
11095      2021.999794  3369.662656       2    65     1232           NaN
11096      2021.999794  3369.662656       2    65     1232           NaN
11097      2021.999794  3369.662656       2    65     1232           NaN
11098      2021.999794  3369.662656       2    65     1232           NaN
11099      2021.999794  3369.662656       2    65     1232           7.0

       totalwgt_lb
11093          NaN
11094          NaN
11095          NaN
11096          NaN
11097          NaN
11098          NaN
11099       7.6875

[7 rows x 245 columns]
(7, 245)
[4 4 4 4 4 4 1]

## Snippet 13- Solve Chapter 1 exercises (value counts, transformation, and filtering)
This snippet applies core data analysis operations to answer exercise questions using the dataset. It computes counts, creates a new variable, and filters specific cases for inspection. These operations mirror common exploratory analysis tasks in real datasets. These tasks reinforce the chapter’s core ideas: counting, transforming, and filtering for data analysis

In [ ]:
"""  
Exercise 1.1: Select the birthord column from preg, print the value counts, and compare to results published in the codebook
at https://ftp.cdc.gov/pub/Health_Statistics/NCHS/Dataset_Documentation/NSFG/Cycle6Codebook-Pregnancy.pdf.

"""


# "birthord" is a serial number for live births. birthord = birth order of that pregnancy. 1.0 → first baby, 2.0 → second baby and so on.
# value_counts() return a Series containing counts of unique values.
# value_count(by default "dropna" = True) which Ignores missing values (NaN)
# .sort_index() aligns results with codebook categories for comparison
# It will sort as many unique categories (index values) as are present in the preg["outcome"] column


birthord=preg["birthord"] # select birth order column
print(birthord)
print(birthord.value_counts().sort_index())


"""     
Interpretation: 
birthord distribution matches the values reported on page 69 of the NSFG codebook; 
NaN values correspond to "inapplicable" cases that are excluded by default in value_counts()

"""

print()

0        1.0
1        2.0
2        1.0
3        2.0
4        3.0
        ...
13588    1.0
13589    NaN
13590    NaN
13591    2.0
13592    3.0
Name: birthord, Length: 13593, dtype: float64
birthord
1.0     4413
2.0     2874
3.0     1234
4.0      421
5.0      126
6.0       50
7.0       20
8.0        7
9.0        2
10.0       1
Name: count, dtype: int64

In [ ]:
"""
Exercise 1.2: Create a new column named totalwgt_kg that contains birth weight in kilograms 
(there are approximately 2.2 pounds per kilogram). Compute the mean and standard deviation of the new column.

"""
# preg = preg.copy()  # defragment the DataFrame so adding a new column is faster and cleaner

preg["totalwgt_kg"] = preg["totalwgt_lb"] / 2.2  # convert total birth weight from pounds to kilograms 

print(preg["totalwgt_kg"].mean())  # compute mean weight in kilograms
print(preg["totalwgt_kg"].std())   # compute standard deviation

3.3174938710161603
0.6972518672856082

In [ ]:
"""   
Exercise 1.3: a) What are the pregnancy lengths for the respondent with caseid 2298?
b)What was the birth weight of the first baby born to the respondent with caseid 5013? 
Hint: You can use "and" to check more than one condition in a query.

"""

""" a) pregnancy lengths for respondent with caseid 2298"""
# prglngth = pregnancy length in weeks.his respondent (caseid = 2298) has 4 pregnancies
# filter rows for this respondent and select pregnancy length column

ID_2298_prglngth = preg.query("caseid == 2298")["prglngth"]  
print(ID_2298_prglngth)


""" b) birth weight of the first baby born to the respondent with caseid 5013"""

# The query() method takes a string that can contain column names, comparison operators, and numbers, among other things.
# filter for specific respondent AND first pregnancy, then select total weight
ID_5013 = preg.query("caseid == 5013 and birthord == 1")["totalwgt_lb"] 
print(ID_5013)


print()


"""    
Interpretation: 
a) The output shows the respondent with caseid 2298 has 4 pregnancies with lengths 40, 36, 30, and 40 weeks.
b) The first baby born to respondent with caseid 5013 has a birth weight of 7.375 pounds (approximately 7 lb 6 oz) 
where 5516 is the row index (Assigned by pandas to Identify a row position in the DataFrame). 
*Noted that row index and case id is not the same thing in NSFG dataset

"""

print()

2610    40
2611    36
2612    30
2613    40
Name: prglngth, dtype: int64
5516    7.375
Name: totalwgt_lb, dtype: float64

"""   
Interpretation
 Exercise 1.1 shows how many pregnancies occurred at each birth order; results should match the codebook distribution.
 Exercise 1.2 creates a new variable in kilograms and computes its mean and spread, confirming unit conversion.
 Exercise 1.3 demonstrates filtering: first query shows all pregnancy lengths for one respondent, while the second isolates a specific condition (first baby) using logical AND.
 
 """